apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base
patchesStrategicMerge:
- patch-deployment.yaml
- patch-configmap.yaml
images:
- name: ghcr.io/prashantsharma18/enterprise-demo
  newTag: latest