
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:workflow-automation, applications, get, */*, allow
    p, role:workflow-automation, applications, sync, */*, allow
    g, workflow-automation, role:workflow-automation

