apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-demo
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: enterprise-demo
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"