# dev-applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: enterprise-demo-dev
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - cluster: in-cluster
          url: https://kubernetes.default.svc
          environment: dev
  template:
    metadata:
      name: 'enterprise-demo-{{environment}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/prashantsharma18/enterprise-demo.git
        targetRevision: HEAD
        path: infra/k8s/overlays/{{environment}}
      destination:
        server: '{{url}}'
        namespace: '{{environment}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true