apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
  - name: success-rate
    interval: 30s
    count: 5
    successCondition: result >= 0.95
    failureCondition: result < 0.95
    provider:
      prometheus:
        address: http://prometheus-operated.monitoring:9090
        query: |
          sum(rate(http_success_total{endpoint!~"metrics|health|ready"}[5m])) 
          /
          sum(rate(http_requests_total{endpoint!~"metrics|health|ready"}[5m]))