apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
  - name: success-rate
    interval: 30s
    count: 2
    successCondition: result >= 0.95
    provider:
      prometheus:
        address: http://prometheus.monitoring:9090
        query: |
          sum(rate(http_requests_total{status=~"2.*", service="enterprise-demo"}[5m])) 
          / 
          sum(rate(http_requests_total{service="enterprise-demo"}[5m]))