apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: enterprise-demo-monitor
  namespace: monitoring  # Prometheus Operator's namespace
spec:
  selector:
    matchLabels:
      app: enterprise-demo
  namespaceSelector:
    matchNames:
    - dev  # Ensure it targets the dev namespace
  endpoints:
  - port: metrics
    interval: 15s
