apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: enterprise-demo
spec:
  selector:
    matchLabels:
      app: enterprise-demo
  endpoints:
  - port: http
    path: /metrics
  namespaceSelector:
    matchNames:
    - dev
    - staging