apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: enterprise-demo-monitor
  namespace: monitoring
  labels:
    release: prometheus  # Add this to match your Prometheus instance
spec:
  selector:
    matchLabels:
      app: enterprise-demo
  namespaceSelector:
    matchNames:
      - dev
  endpoints:
    - port: http
      interval: 15s
      path: /metrics  # Explicitly specify the path