apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- ../../base
patchesStrategicMerge:
- patch-deployment.yaml
- patch-configmap.yaml
- rollout-patch.yaml
images:
- name: ghcr.io/prashantsharma18/enterprise-demo
  newTag: aa505f329f4e6056ff25fcd498a68e7af066aee6